// Tool labels live here rather than in the global dictionary: they are only ever used on this screen,
// and keeping the pair next to the tool makes it obvious when one side is missing.
export const L = {
  tools:      { he: 'כלי עזר', en: 'Tools' },
  tools_sub:  { he: 'מחשבונים לשטח — לא נכנסים לרשימה ולא להדפסה', en: 'Field calculators — they stay out of the list and out of the print' },
  media:      { he: 'מדיה', en: 'Media' },
  media_sub:  { he: 'כמה כרטיסים ליום צילום', en: 'How many cards a shoot day needs' },
  fov:        { he: 'בחירת עדשה', en: 'Lens choice' },
  fov_sub:    { he: 'איזה מוקד מכסה את הפריים מהמרחק הזה', en: 'Which focal length covers the frame from there' },
  shutter:    { he: 'פריים רייט ושאטר', en: 'Frame rate & shutter' },
  shutter_sub:{ he: 'זווית תריס, מהירות, ופליקר', en: 'Shutter angle, speed and flicker' },
  offload:    { he: 'זמן העתקה', en: 'Offload time' },
  offload_sub:{ he: 'כמה זמן ייקח הדאמפ בסוף היום', en: 'How long the dump takes at wrap' },
  sun:        { he: 'שקיעה וזריחה', en: 'Sun times' },
  sun_sub:    { he: 'שעת זהב, שעה כחולה, אורך יום', en: 'Golden hour, blue hour, day length' },
  units:      { he: 'המרת מידות', en: 'Unit conversion' },
  units_sub2: { he: '', en: '' },
  luts:       { he: 'מאגר לוטים', en: 'LUT bank' },
  luts_sub:   { he: 'איזה לוט הולך עם איזה לוג, ומאיפה מורידים', en: 'Which LUT goes with which log, and where to get it' },
  lut_pick:   { he: 'בחר מצלמה — נראה איזה לוג היא מצלמת ואיפה היצרן מפרסם את הלוט', en: 'Pick a camera — see the log it records and where its maker publishes the LUT' },
  lut_records:{ he: '{cam} מצלמת', en: '{cam} records' },
  lut_monitor:{ he: 'לניטור על הסט', en: 'Monitor with' },
  lut_download:{ he: 'הורדת הלוטים הרשמיים', en: 'Download the official LUTs' },
  lut_also:   { he: 'גם', en: 'Also' },
  lut_files:  { he: 'לוטים', en: 'LUTs' },
  brand_pick: { he: 'מותג', en: 'Brand' },
  country: { he: 'מדינה', en: 'Country' },
  iso: { he: 'ISO בסיס', en: 'Base ISO' },
  iso_sub: { he: 'הבסיס של כל מצלמה, ממקור רשמי', en: 'Each camera\'s base ISO, from the maker' },
  iso_one: { he: 'ISO בסיס', en: 'Base ISO' },
  iso_low: { he: 'בסיס נמוך', en: 'Low base' },
  iso_high: { he: 'בסיס גבוה', en: 'High base' },
  iso_third: { he: 'בסיס שלישי', en: 'Third base' },
  iso_pending: { he: 'עוד לא נמצא מקור רשמי לערך הזה — לא מנחשים.', en: 'No official source for this value yet — we don\'t guess.' },
  iso_yours: { he: 'באיזה ISO תעבוד?', en: 'Which ISO will you shoot at?' },
  iso_at: { he: 'בדיוק על בסיס {b}', en: 'right on the {b} base' },
  iso_off: { he: '{d} סטופים מהבסיס {b}', en: '{d} stops from the {b} base' },
  iso_src: { he: 'מקור', en: 'Source' },
  iso_cmp_open: { he: 'השווה עם עוד מצלמות', en: 'Compare with more cameras' },
  iso_cmp_close: { he: 'סגור השוואה', en: 'Close comparison' },
  iso_cmp: { he: 'המצלמות בצילום', en: 'Cameras on the shoot' },
  iso_add: { he: '+ הוסף מצלמה', en: '+ Add a camera' },
  iso_meet: { he: 'נקודת מפגש: כולן בבסיס ב־ISO {b}', en: 'Meeting point: all at base at ISO {b}' },
  iso_near: { he: 'אין בסיס משותף לכולן — הכי קרוב: ISO {b}', en: 'No base shared by all — closest: ISO {b}' },
  iso_note: { he: 'בבסיס החיישן נותן את הטווח הדינמי המלא עם הכי מעט רעש. ב־RED ה־ISO הוא מטא־דאטה, והערך הוא ברירת המחדל של היצרן.', en: 'At base the sensor gives its full dynamic range with the least noise. On RED, ISO is metadata and the value is the maker\'s default.' },
  slate: { he: 'סלייט וטיים־קוד', en: 'Slate & timecode' },
  slate_sub: { he: 'שעון טיים־קוד, סצנה וטייק, קלאפ לסנכרון', en: 'Timecode clock, scene and take, a clap to sync' },
  sl_scene: { he: 'סצנה', en: 'Scene' },
  sl_take: { he: 'טייק', en: 'Take' },
  sl_roll: { he: 'רול', en: 'Roll' },
  sl_clap: { he: 'קלאפ', en: 'Clap' },
  sl_full: { he: 'מסך מלא למצלמות', en: 'Full screen for the cameras' },
  sl_more: { he: 'סאונד, אזור זמן ודיוק', en: 'Sound, time zone and accuracy' },
  sl_sound: { he: 'סאונד הקלאפ', en: 'Clap sound' },
  sl_sticks: { he: 'מקלות סלייט', en: 'Slate sticks' },
  sl_beep: { he: 'צפצוף 1 kHz', en: '1 kHz beep' },
  sl_zone: { he: 'אזור זמן', en: 'Time zone' },
  sl_zone_local: { he: 'השעון של הטלפון', en: 'Phone time' },
  sl_fine: { he: 'כיוון עדין', en: 'Fine offset' },
  sl_frames: { he: 'פריימים', en: 'frames' },
  sl_check: { he: 'בדיקת דיוק השעון', en: 'Clock accuracy' },
  sl_check_why: { he: 'דפדפן לא יכול לקרוא את שעון ה־GPS. השעון של הטלפון מסונכרן מהרשת (ובאנדרואיד לרוב גם מהלוויינים), ובדיקה מול שרת זמן מראה בכמה הוא סוטה ועד כמה התשובה בטוחה.', en: 'A browser cannot read GPS time. The phone\'s clock is network-synced (on Android often from the satellites too); a check against a time server shows how far off it is and how sure the answer is.' },
  sl_check_btn: { he: 'בדוק מול שרת זמן', en: 'Check against a time server' },
  sl_check_res: { he: 'השעון של הטלפון {dir} ב־{s} שנ׳ (דיוק הבדיקה ±{pm} שנ׳)', en: 'The phone clock is {dir} by {s} s (check accurate to ±{pm} s)' },
  sl_ahead: { he: 'מקדים', en: 'ahead' },
  sl_behind: { he: 'מאחר', en: 'behind' },
  sl_check_fail: { he: 'אין חיבור לשרת הזמן כרגע. נסה שוב כשיש רשת.', en: 'No connection to the time server right now. Try again with a network.' },
  sl_apply: { he: 'תקן לפי השרת', en: 'Correct to the server' },
  sl_corrected: { he: 'מתוקן לפי שרת', en: 'server-corrected' },
  sl_uncorrect: { he: 'בטל תיקון', en: 'Undo correction' },
  sl_note: { he: 'הטיים־קוד הוא שעון היום. לסנכרון מדויק בעריכה — ההבזק והקלאפ מסמנים את אותו פריים בתמונה ובסאונד.', en: 'This is time-of-day timecode. For exact sync in the edit, the flash and the clap mark the same frame in picture and sound.' },
  sl_src_tod: { he: 'שעון היום', en: 'Time of day' },
  sl_src_jam: { he: 'ידני (ג׳ם)', en: 'Manual (jam)' },
  sl_jam_btn: { he: 'הרץ מכאן', en: 'Run from here' },
  sl_jam_hint: { he: 'הקלד את הטיים־קוד שמופיע במצלמה, בטנטקל או במקליט, ולחץ "הרץ מכאן" בדיוק כשהשנייה שם מתחלפת. מכאן הוא רץ לבד.', en: 'Type the timecode showing on the camera, Tentacle or recorder, and press "Run from here" just as its second ticks over. It runs on its own from there.' },
  sl_jam_running: { he: 'רץ מהערך שהוזן. כמו כל ג׳ם ידני, הדיוק תלוי ברגע הלחיצה, ושעון הטלפון זוחל לאט — כדאי לג׳ם מחדש בתחילת כל יום.', en: 'Running from the typed value. Like any hand jam, it is as exact as the moment you pressed, and a phone clock drifts slowly — jam again at the start of each day.' },
  sl_jam_bad: { he: 'הערך לא תקין: שעות, דקות, שניות ופריים, למשל 10:00:00:00, ובלי פריים שלא קיים בקצב הזה.', en: 'The format is HH:MM:SS:FF, e.g. 10:00:00:00 (no frame that does not exist at this rate).' },
  sl_tap: { he: 'נגיעה בכל מקום — קלאפ', en: 'Tap anywhere to clap' },
  sl_digits: { he: 'רק ספרות', en: 'Digits only' },
  sl_board: { he: 'עם סצנה וטייק', en: 'With scene and take' },
  hours: { he: 'דוח שעות', en: 'Hours report' },
  hours_sub: { he: 'קול טיים, ראפ, שעות נוספות וטרנאראונד', en: 'Call, wrap, overtime and turnaround' },
  call_time: { he: 'קול טיים', en: 'Call time' },
  wrap_time: { he: 'ראפ', en: 'Wrap' },
  break_min: { he: 'הפסקות (דקות)', en: 'Breaks (minutes)' },
  turnaround_h: { he: 'טרנאראונד נדרש', en: 'Required turnaround' },
  worked: { he: 'שעות עבודה', en: 'Hours worked' },
  next_call: { he: 'הקול המוקדם ביותר מחר', en: 'Earliest call tomorrow' },
  next_day: { he: 'למחרת', en: 'next day' },
  hr_regular: { he: 'רגילות', en: 'regular' },
  hr_at:      { he: 'ב־{p}%', en: 'at {p}%' },
  hr_pay:     { he: 'לתשלום', en: 'Pay' },
  hr_pay_split: { he: 'יום {day} + נוספות {ot}', en: 'day {day} + overtime {ot}' },
  hr_rest:    { he: '{h} שעות מנוחה', en: '{h} h rest' },
  hr_times:   { he: 'שעות', en: 'Times' },
  hr_breaks:  { he: 'הפסקות', en: 'Breaks' },
  hr_rules:   { he: 'שעות נוספות', en: 'Overtime' },
  hr_day:     { he: 'יום עבודה', en: 'Day length' },
  hr_first:   { he: 'תעריף ראשון', en: 'First tier' },
  hr_after:   { he: 'אחר כך', en: 'After that' },
  hr_rate:    { he: 'תעריף יומי (לא חובה)', en: 'Day rate (optional)' },
  hr_rate_note: { he: 'התעריף היומי מכסה את שעות היום; השעות הנוספות מחושבות לפי התעריף השעתי שיוצא ממנו', en: 'The day rate covers the day’s hours; overtime is paid on the hourly rate it implies' },
  u_length: { he: 'אורך', en: 'Length' }, u_weight: { he: 'משקל', en: 'Weight' }, u_data: { he: 'נתונים', en: 'Data' }, u_rate: { he: 'קצב', en: 'Rate' },
  u_battery: { he: 'סוללה', en: 'Battery' }, u_nd: { he: 'ND', en: 'ND' }, u_temp: { he: 'טמפרטורה', en: 'Temperature' },
  fly_ok:     { he: 'מותרת בטיסה — בתיק היד', en: 'Allowed on a flight — in carry-on' },
  fly_approval: { he: 'מעל 100Wh — רק באישור חברת התעופה, עד 2 רזרביות', en: 'Over 100 Wh — only with the airline’s approval, two spares at most' },
  fly_no:     { he: 'מעל 160Wh — אסורה בכבודת נוסע', en: 'Over 160 Wh — not allowed in passenger baggage' },
  fly_src_short: { he: 'כללי ליתיום לנוסעים', en: 'lithium rules for passengers' },
  fly_src:    { he: 'IATA: סוללת ליתיום־יון עד 100Wh מותרת בתיק היד; 100–160Wh באישור חברת התעופה (עד שתי רזרביות); מעל 160Wh אסורה בכבודת נוסע. רזרביות תמיד בתיק היד. בדוק גם את חברת התעופה שלך.', en: 'IATA: lithium-ion up to 100 Wh is allowed in carry-on; 100–160 Wh with the airline’s approval (two spares at most); over 160 Wh not in passenger baggage. Spares always in carry-on. Check your airline too.' },
  nd_density: { he: 'צפיפות', en: 'Density' }, nd_factor: { he: 'מקדם', en: 'Factor' }, nd_stops: { he: 'סטופים', en: 'Stops' }, nd_light: { he: 'אור שעובר', en: 'Light through' },
  lut_disclaimer: { he: 'הערות החשיפה הן נוהג מקובל על הסט, לא הוראה של היצרן. תמיד בדוק על הגוף שלך.', en: 'Exposure notes are common practice on set, not manufacturer instruction. Always test on your own body.' },
  units_sub:  { he: 'מטרי ואימפריאלי, נתונים, סוללות', en: 'Metric and imperial, data, batteries' },

  codec: { he: 'קודק', en: 'Codec' },
  camera_pick: { he: 'מצלמה', en: 'Camera' },
  format_pick: { he: 'פורמט', en: 'Format' },
  manual_fmt: { he: 'בחירה ידנית', en: 'Choose manually' },
  res: { he: 'רזולוציה', en: 'Resolution' },
  fps: { he: 'פריים רייט', en: 'Frame rate' },
  card: { he: 'גודל כרטיס', en: 'Card size' },
  bitrate: { he: 'קצב נתונים', en: 'Data rate' },
  per_hour: { he: 'לשעה', en: 'Per hour' },
  on_card: { he: 'על כרטיס אחד', en: 'On one card' },
  cards_needed: { he: 'כרטיסים ליום', en: 'Cards per day' },
  shoot_hours: { he: 'שעות צילום ביום', en: 'Shoot hours per day' },
  source: { he: 'מקור', en: 'Source' },

  sensor_f: { he: 'פורמט חיישן', en: 'Sensor format' },
  from_camera: { he: 'לפי מצלמה מהמאגר', en: 'From a camera in the catalog' },
  any_camera: { he: 'בחירה חופשית', en: 'Free choice' },
  matching_lenses: { he: 'עדשות שמתאימות', en: 'Lenses that fit' },
  no_lenses: { he: 'לא נמצאו עדשות מתאימות במאגר', en: 'No matching lenses in the catalog' },
  lens_count: { he: '{n} מהמאגר', en: '{n} in the catalog' },
  distance: { he: 'מרחק (מטר)', en: 'Distance (m)' },
  subject: { he: 'גודל פריים', en: 'Frame size' },
  frame_w: { he: 'רוחב פריים (מטר)', en: 'Frame width (m)' },
  need_lens: { he: 'המוקד הדרוש', en: 'Focal length needed' },
  nearest: { he: 'העדשה הקרובה בסט', en: 'Nearest prime in the set' },
  lens_note: { he: 'מסומנות העדשות שמכסות את המוקד הזה', en: 'The lenses that cover this focal length are marked' },
  covers: { he: 'מכסה', en: 'Covers' },
  angle_h: { he: 'זווית אופקית', en: 'Horizontal angle' },
  check_lens: { he: 'בדיקה הפוכה — מה עדשה נתונה מכסה', en: 'The other way round — what a given lens covers' },
  framing: { he: 'איך זה ייראה', en: 'How it frames' },
  person_note: { he: 'הדמות בגובה 1.75 מ׳ — לפי זה אפשר לקרוא את הפריים', en: 'The figure is 1.75 m — read the frame against it' },
  viewfinder: { he: 'ויופיינדר חי', en: 'Live viewfinder' },
  vf_start: { he: 'פתח את מצלמת הטלפון', en: 'Open the phone camera' },
  vf_ruler: { he: 'בחירת מוקד', en: 'Focal length' },
  rec_format: { he: 'פורמט צילום', en: 'Recording format' },
  sun_place_date: { he: 'מקום ותאריך', en: 'Place and date' },
  sun_acc: { he: 'דיוק של כדקה, לפי משוואות NOAA. הרים ומבנים בכיוון השמש מקדימים את השקיעה בפועל.', en: 'Accurate to about a minute (NOAA equations). Hills and buildings toward the sun bring the actual sunset earlier.' },
  media_more: { he: 'פורמט, פריים רייט, כרטיס ושעות', en: 'Format, frame rate, card and hours' },
  sh_more: { he: 'שאטר, חשמל ופרויקט', en: 'Shutter, mains and project' },
  off_more: { he: 'עותקים, אימות וחיבורים', en: 'Copies, verify and connections' },
  hr_rules_rate: { he: 'חוקי שעות ותעריף (נשמרים)', en: 'Hours rules and rate (kept)' },
  downloads: { he: 'הורדות', en: 'Downloads' },
  downloads_sub: { he: 'עדכוני תוכנה, LUTs ותוכנות — מהיצרנים', en: 'Firmware, LUTs and software — from the makers' },
  dl_firmware: { he: 'עדכון תוכנה', en: 'Firmware' },
  dl_software: { he: 'תוכנה', en: 'Software' },
  dl_fw_manual: { he: 'עדכון ומדריך', en: 'Firmware & manual' },
  dl_app: { he: 'אפליקציה', en: 'App' },
  dl_open: { he: 'להורדה', en: 'Download' },
  dl_new: { he: 'חדש', en: 'New' },
  dl_none: { he: 'לא נמצא — נסה שם אחר', en: 'Nothing found — try another name' },
  dl_search_ph: { he: 'חיפוש: מצלמה, מוניטור, תוכנה…', en: 'Search: camera, monitor, software…' },
  dl_lut_finder: { he: 'מציאת LUT לפי מצלמה ←', en: 'Find a LUT by camera →' },
  dl_note: { he: 'כל הקישורים לעמודים הרשמיים של היצרנים, ונבדקו ידנית. גרסה עדכנית — בעמוד היצרן.', en: 'Every link goes to the maker’s own page and was checked by hand. The current version is on the maker’s page.' },
  cam_yours: { he: 'המצלמות שלך', en: 'Your cameras' },
  cam_search_ph: { he: 'הקלד מצלמה: fx9, venice, alexa…', en: 'Type a camera: fx9, venice, alexa…' },
  cam_hits: { he: '{n} תוצאות', en: '{n} results' },
  cam_none: { he: 'לא נמצאה מצלמה בשם הזה', en: 'No camera by that name' },
  cam_from_project: { he: 'פרויקט', en: 'project' },
  cam_recent: { he: 'לאחרונה', en: 'recent' },
  cam_now: { he: 'עכשיו', en: 'now' },
  cancel_pick: { he: 'השאר את המצלמה הנוכחית', en: 'Keep the current camera' },
  vf_switch_cam: { he: 'החלפת מצלמה', en: 'Switch camera' },
  firmware: { he: 'עדכון תוכנה אחרון', en: 'Latest firmware' },
  n_formats: { he: '{n} פורמטים', en: '{n} formats' },
  mode_approx: { he: 'היצרן מפרסם את המצב הזה כיחס קרופ ולא במ״מ — הגודל מחושב ממנו', en: 'The maker gives this mode as a crop factor, not in mm — the size is worked out from it' },
  sensor_format: { he: 'פורמט חיישן', en: 'Sensor format' },
  fmt_FF: { he: 'פול־פריים', en: 'Full frame' },
  fmt_S35: { he: 'Super 35', en: 'Super 35' },
  fmt_MFT: { he: 'MFT', en: 'MFT' },
  frame_at: { he: '{mm} מ״מ מ־{d} {u}: פריים {w} × {h} {u}', en: '{mm} mm from {d} {u}: frame {w} × {h} {u}' },
  vf_at: { he: 'מ־{d} {u}: {w} × {h} {u}', en: 'At {d} {u}: {w} × {h} {u}' },
  lens_now: { he: 'עדשה', en: 'Lens' },
  mon_look: { he: 'מראה מוניטור', en: 'Monitor look' },
  vf_cal_btn: { he: 'בדיקת דיוק וכיול', en: 'Check and calibrate' },
  vf_cal_chip: { he: 'לא מכויל · ±10% · כיול', en: 'Not calibrated · ±10% · calibrate' },
  vf_cal_ok: { he: 'מכויל לטלפון הזה: רואה כמו עדשה של {eq} מ״מ', en: 'Calibrated for this phone: sees like a {eq} mm lens' },
  vf_cal_none: { he: 'המסגרת בעינית מבוססת על הערכה של מצלמת טלפון ממוצעת (26 מ״מ) ויכולה לסטות בכ־10% בטלפון שלך. כיול של דקה עם דף A4 מתאים אותה בדיוק לטלפון שלך.', en: 'The viewfinder frame is based on an average phone camera (26 mm) and can be about 10% off on your phone. A one-minute calibration with an A4 sheet fits it exactly to your phone.' },
  vf_cal_how: { he: 'הדבק דף A4 לרוחב על קיר ועמוד בדיוק מטר אחד ממנו (מדוד מהטלפון לקיר). הזז את הפס עד שהמסגרת הלבנה נוגעת בדיוק בקצוות הדף.', en: 'Tape an A4 sheet sideways to a wall and stand exactly 1 m away (measure from the phone to the wall). Move the slider until the white box just touches the sheet\'s edges.' },
  vf_cal_dist: { he: 'מרחק (מ׳)', en: 'Distance (m)' },
  vf_cal_width: { he: 'רוחב החפץ (ס״מ)', en: 'Object width (cm)' },
  vf_cal_result: { he: 'הטלפון רואה כמו עדשה של {eq} מ״מ ({diff} מההערכה)', en: 'Your phone sees like a {eq} mm lens ({diff} from the estimate)' },
  vf_cal_save: { he: 'שמור כיול', en: 'Save calibration' },
  vf_cal_reset: { he: 'חזרה להערכה', en: 'Back to the estimate' },
  vf_cal_saved: { he: 'נשמר. המסגרות מחושבות עכשיו לפי הטלפון שלך.', en: 'Saved. Frames now use your phone\'s own angle.' },
  lens_for_shot: { he: 'איזו עדשה לשוט? לחיצה מסובבת את הטבעת', en: 'Which lens for a shot? Tap to turn the ring' },
  lens_wider: { he: 'עדשה רחבה יותר', en: 'Wider lens' },
  lens_longer: { he: 'עדשה ארוכה יותר', en: 'Longer lens' },
  vf_hold: { he: 'גוללים את החוגה או מחליקים על התמונה. החזקה ארוכה על עדשה מוסיפה אותה להשוואה — עד שלוש, כל אחת בצבע משלה.', en: 'Turn the dial or swipe the picture. Hold a lens to add it to the comparison — up to three, each in its own colour.' },
  vf_cmp_clear: { he: 'בטל השוואה', en: 'Clear comparison' },
  vf_fps: { he: 'פריים רייט — לחיצה מחליפה', en: 'Frame rate — tap to change' },
  vf_info_hide: { he: 'הסתר את נתוני המרחק', en: 'Hide the distance data' },
  vf_info_show: { he: 'הצג את נתוני המרחק', en: 'Show the distance data' },
  vf_rec: { he: 'הקלטת קליפ של הפריים', en: 'Record a clip of the frame' },
  vf_rec_stop: { he: 'עצור הקלטה', en: 'Stop recording' },
  vf_grab: { he: 'צלם פריים', en: 'Grab frame' },
  vf_share: { he: 'שלח לבמאי או שמור בגלריה', en: 'Send to the director or save to photos' },
  vf_grabbed: { he: 'צולם. לחיצה על התמונה הקטנה — שמירה בטלפון או שליחה לבמאי.', en: 'Grabbed. Tap the thumbnail to save it or send it to the director.' },
  vf_recorded: { he: 'הקליפ מוכן. לחיצה על התמונה הקטנה — שמירה או שליחה.', en: 'Clip ready. Tap the thumbnail to save or send it.' },
  vf_save: { he: 'שמור בטלפון', en: 'Save to phone' },
  vf_send: { he: 'שלח לבמאי', en: 'Send to director' },
  vf_saved_dl: { he: 'נשמר בהורדות — בגלריה הוא מופיע בתיקייה Download.', en: 'Saved to Downloads — your gallery shows it under Download.' },
  vf_saved_files: { he: 'נשמר בקבצים (Files) ← הורדות.', en: 'Saved to Files → Downloads.' },
  vf_turn: { he: 'החלפה בין רוחב לאורך', en: 'Switch between landscape and portrait' },
  vf_to_landscape: { he: 'לרוחב', en: 'Landscape' },
  vf_to_portrait: { he: 'לאורך', en: 'Portrait' },
  maker: { he: 'יצרן', en: 'Maker' },
  vf_rotate: { he: 'העדשה הזו רחבה מהטלפון כשהוא עומד — סובב את הטלפון לרוחב ותראה את כל הפריים.', en: 'This lens is wider than the phone held upright — turn the phone sideways to see the whole frame.' },
  calc_by_distance: { he: 'חישוב לפי מרחק וגודל שוט', en: 'Work it out from distance and shot size' },
  in_catalog: { he: 'במאגר', en: 'In the catalog' },
  from_project: { he: 'מהפרויקט הפעיל', en: 'From the active project' },
  change: { he: 'החלפה', en: 'Change' },
  vf_stop: { he: 'סגור', en: 'Close' },
  vf_hint: { he: 'רואים במצלמת הטלפון מה כל עדשה תתפוס על {cam} מהמקום שאתה עומד בו. גוללים בין העדשות והמסגרת משתנה בלייב.', en: 'See on your phone camera what each lens takes in on the {cam} from where you stand. Scroll through lenses and the frame follows live.' },
  vf_wider: { he: 'העדשה הזו רחבה יותר ממה שהטלפון רואה — כל המסך בתוך הפריים. התרחק או בחר עדשה ארוכה יותר.', en: 'This lens is wider than the phone sees — the whole screen is inside the frame. Step back or pick a longer lens.' },
  vf_denied: { he: 'אין גישה למצלמה. צריך לאשר הרשאה בדפדפן.', en: 'No camera access. The browser needs permission.' },
  vf_err_inapp: { he: 'הדפדפן הזה לא מאפשר מצלמה — כנראה נפתח מתוך וואטסאפ/אינסטגרם. פתח את הקישור ב-Safari (או בכרום) ונסה שוב.', en: 'This browser can’t use the camera — it was probably opened inside WhatsApp or Instagram. Open the link in Safari (or Chrome) and try again.' },
  vf_err_denied_ios: { he: 'הגישה למצלמה נחסמה. באייפון: לחץ על "aA" בשורת הכתובת ← הגדרות אתר ← מצלמה ← אפשר. או: הגדרות ← Safari ← מצלמה ← אפשר.', en: 'Camera access is blocked. On iPhone: tap "aA" in the address bar → Website Settings → Camera → Allow. Or Settings → Safari → Camera → Allow.' },
  vf_err_denied: { he: 'הגישה למצלמה נחסמה. לחץ על סמל המנעול ליד הכתובת ← הרשאות ← מצלמה ← אפשר, ונסה שוב.', en: 'Camera access is blocked. Tap the lock by the address → Permissions → Camera → Allow, and try again.' },
  vf_err_nocam: { he: 'לא נמצאה מצלמה במכשיר.', en: 'No camera was found on this device.' },
  vf_approx: { he: 'הערכה לפי המצלמה הראשית של הטלפון (1×). גוללים בפס או מחליקים על התמונה.', en: 'An estimate based on the phone’s main (1×) camera. Scroll the strip or swipe the picture.' },
  focal: { he: 'מוקד (מ״מ)', en: 'Focal length (mm)' },
  camera_step: { he: 'מצלמה', en: 'Camera' },
  distance_step: { he: 'מרחק מהמצולם', en: 'Distance to subject' },
  shot_step: { he: 'סוג שוט', en: 'Shot size' },
  meters: { he: 'מ׳', en: 'm' },
  feet: { he: 'רגל', en: 'ft' },
  verified_only: { he: 'מופיעות רק מצלמות שגודל החיישן שלהן אומת מול היצרן', en: 'Only cameras whose sensor size has been verified with the maker are listed' },
  sensor_line: { he: 'חיישן {w}×{h} מ״מ · {mode}', en: 'Sensor {w}×{h} mm · {mode}' },
  choose_camera_first: { he: 'בחר מצלמה — לפי החיישן שלה נחשב איזו עדשה צריך', en: 'Pick a camera — its sensor decides which lens you need' },
  need_sentence: { he: 'מ־{d} {u}, שוט {shot} על {cam} — מדויק: {mm} מ״מ', en: 'From {d} {u}, a {shot} on {cam} — exactly {mm} mm' },
  frame_line: { he: 'הפריים: {w}×{h} {u} · זווית {a}°', en: 'Frame: {w}×{h} {u} · {a}° wide' },
  lenses_for: { he: 'עדשות מהמאגר שמתאימות ל־{cam}', en: 'Lenses in the catalog that fit {cam}' },
  standard_primes: { he: 'פריימים סטנדרטיים', en: 'Standard primes' },
  tap_lens_hint: { he: 'לחיצה על עדשה מראה בציור מה היא נותנת', en: 'Tap a lens to see what it gives in the drawing' },
  prime_lbl: { he: 'עדשה קבועה', en: 'Prime' },
  zoom_lbl: { he: 'זום', en: 'Zoom' },
  back_to_rec: { he: 'חזרה להמלצה ({mm} מ״מ)', en: 'Back to the pick ({mm} mm)' },

  angle: { he: 'זווית תריס', en: 'Shutter angle' },
  speed: { he: 'מהירות תריס', en: 'Shutter speed' },
  mains: { he: 'תדר רשת החשמל', en: 'Mains frequency' },
  flicker_ok: { he: 'נקי מפליקר', en: 'Flicker free' },
  flicker_bad: { he: 'עלול להבהב בתאורת רשת', en: 'May flicker under mains light' },
  safe_angles: { he: 'זוויות בטוחות בפריים רייט הזה', en: 'Safe angles at this frame rate' },
  project_fps: { he: 'פריים רייט של הפרויקט', en: 'Project frame rate' },
  shutter_lbl: { he: 'שאטר', en: 'Shutter' },
  media_pick_first: { he: 'בחר מצלמה — הפורמטים והקצבים מגיעים מהיצרן שלה', en: 'Pick a camera — its formats and rates come from its maker' },
  cards_of:   { he: 'כרטיסים של {card}', en: 'cards of {card}' },
  media_sentence: { he: '{h} שעות {fmt} ב־{fps} על {cam} = {total}. כרטיס אחד מחזיק {per}.', en: '{h} hours of {fmt} at {fps} on {cam} = {total}. One card holds {per}.' },
  src_official: { he: 'נתון רשמי', en: 'Official' },
  src_estimate: { he: 'הערכה', en: 'Estimate' },
  max_rate:   { he: 'עד {r} Mbps — הקצב המרבי שהיצרן מפרסם, לכן החישוב מחמיר (לעולם לא חסר)', en: 'up to {r} Mbps — the maximum the maker publishes, so this errs on the safe side' },
  cap_rate:   { he: '{r} Mbps — התקרה של המצלמה ({mb} MB/s), כך שבקצב הזה ה־R3D נדחס יותר', en: '{r} Mbps — the camera’s top write speed ({mb} MB/s), so R3D compresses harder at this rate' },
  usable_note: { he: '(בפועל {u} לכרטיס)', en: '({u} usable per card)' },
  backup_lbl: { he: 'גיבוי — הקלטה לשני הכרטיסים במקביל', en: 'Backup — record to both slots at once' },
  backup_note: { he: 'עם גיבוי, כל טייק נשמר על שני כרטיסים.', en: 'With backup, every take is on two cards.' },
  to_offload: { he: 'כמה זמן לפרוק {total}? ←', en: 'Offload time for {total} →' },
  src_more:   { he: 'מקור', en: 'Source' },
  card_src:   { he: 'גדלי כרטיסים: {s}', en: 'Card sizes: {s}' },
  eff_rate:   { he: '≈{r} Mbps בפועל, לפי זמני ההקלטה של היצרן', en: '≈{r} Mbps effective, from the maker’s recording times' },
  speed_short: { he: 'מהירות', en: 'Speed' },
  angle_short: { he: 'זווית', en: 'Angle' },
  recommended: { he: 'מומלץ', en: 'best' },
  other_val:  { he: 'אחר…', en: 'Other…' },
  mains_50:   { he: '50Hz · ישראל ואירופה', en: '50 Hz · Israel & Europe' },
  mains_60:   { he: '60Hz · ארה״ב', en: '60 Hz · USA' },
  sh_safe:    { he: 'לא יהבהב בתאורת חשמל של {hz}Hz', en: 'No flicker under {hz} Hz mains light' },
  sh_unsafe:  { he: 'עלול להבהב בתאורת חשמל של {hz}Hz — עדיף {rec}', en: 'May flicker under {hz} Hz mains light — use {rec}' },
  sh_none:    { he: 'בפריים רייט הזה אין שאטר שלא מהבהב ב־{hz}Hz — צריך תאורה בלי הבהוב (LED איכותי או HMI אלקטרוני)', en: 'No shutter at this frame rate avoids {hz} Hz flicker — use flicker-free lights (good LED or electronic HMI)' },
  sh_realtime: { he: 'מהירות רגילה', en: 'real time' },
  sh_slow:    { he: 'הילוך איטי פי {n}', en: '{n}× slow motion' },
  sh_fast:    { he: 'הילוך מהיר פי {n}', en: '{n}× fast motion' },
  sh_hint:    { he: '✓ = לא מהבהב בתאורת חשמל. "מומלץ" = הכי קרוב ל־180°, התנועה הטבעית שהעין רגילה אליה.', en: '✓ = no mains flicker. "best" = nearest to 180°, the motion blur the eye is used to.' },
  slowmo: { he: 'סלואו מושן', en: 'Slow motion' },

  footage: { he: 'כמות חומר', en: 'Footage' },
  off_source: { he: 'מקור — הכרטיס בקורא', en: 'Source — the card in its reader' },
  off_for:    { he: 'שעות לפריקת {gb}', en: 'to offload {gb}' },
  off_sentence: { he: '{gb} מ־{src} אל {dst}, {n} עותקים אחד אחרי השני.', en: '{gb} from {src} to {dst}, {n} copies one after another.' },
  off_verify: { he: 'כל עותק נקרא בחזרה לאימות.', en: 'Each copy is read back to verify it.' },
  off_noverify: { he: 'בלי אימות.', en: 'No verify.' },
  off_each:   { he: '{n} מעברים × {t} · צריך {space} בכוננים', en: '{n} passes × {t} · needs {space} across the drives' },
  off_limit_src: { he: 'הקורא הוא צוואר הבקבוק — כונן מהיר יותר לא יקצר.', en: 'The card reader sets the pace — a faster drive won’t help.' },
  off_limit_src2: { he: 'הקוראים הם צוואר הבקבוק — כונן מהיר יותר לא יקצר.', en: 'The card readers set the pace — a faster drive won’t help.' },
  off_limit_port: { he: 'יציאת המחשב היא צוואר הבקבוק — יציאה מהירה יותר תקצר.', en: 'The computer’s port sets the pace — a faster port would cut the time.' },
  off_per_card: { he: 'בכל החלפת כרטיס: {card} לוקח {t}, כולל העותקים.', en: 'Each card change: {card} takes {t}, copies included.' },
  off_readers: { he: 'קוראים במקביל', en: 'Readers at once' },
  off_port:   { he: 'יציאה במחשב', en: 'Computer port' },
  off_limit_dst: { he: 'הכונן הוא צוואר הבקבוק — כונן מהיר יותר יקצר את הזמן.', en: 'The drive sets the pace — a faster drive would cut the time.' },
  off_maker:  { he: 'נתון יצרן', en: 'Maker spec' },
  off_caveat: { he: 'המהירות המרבית שהיצרן מפרסם — בפועל זה לרוב קצת יותר לאט', en: 'the top speed the maker publishes — real offloads usually run a little slower' },
  off_from_media: { he: 'מכלי המדיה: יום הצילום שחישבת', en: 'From the media tool: the shoot day you worked out' },
  drive: { he: 'יעד', en: 'Destination' },
  copies: { he: 'מספר עותקים', en: 'Copies' },
  verify: { he: 'כולל אימות', en: 'Verify each copy' },

  place: { he: 'מקום', en: 'Place' },
  date: { he: 'תאריך', en: 'Date' },
  my_location: { he: 'המיקום שלי', en: 'My location' },
  sunrise: { he: 'זריחה', en: 'Sunrise' },
  sunset: { he: 'שקיעה', en: 'Sunset' },
  golden_am: { he: 'שעת זהב · בוקר', en: 'Golden hour · morning' },
  golden_pm: { he: 'שעת זהב · ערב', en: 'Golden hour · evening' },
  blue_am: { he: 'שעה כחולה · בוקר', en: 'Blue hour · morning' },
  blue_pm: { he: 'שעה כחולה · ערב', en: 'Blue hour · evening' },
  noon: { he: 'שיא היום', en: 'Solar noon' },
  day_len: { he: 'אורך יום', en: 'Day length' },
  sun_at:     { he: 'שקיעה · {place} · {day}', en: 'sunset · {place} · {day}' },
  sun_morning: { he: 'בוקר: זריחה {rise} · שעת זהב {gold} · שעה כחולה {blue} · אורך היום {len}', en: 'Morning: sunrise {rise} · golden {gold} · blue {blue} · day length {len}' },
  tz_note:    { he: 'השעות לפי השעון המקומי ב{place} ({tz})', en: 'Times are local to {place} ({tz})' },
  sun_calc:   { he: 'מחושב לפי משוואות השמש של NOAA', en: 'worked out with NOAA’s solar equations' },
  sun_src:    { he: 'זריחה ושקיעה: מרכז השמש 0.833° מתחת לאופק (כולל שבירת אור). שעת זהב: השמש עד 6° מעל האופק. שעה כחולה: השמש בין 0° ל־6° מתחת לאופק (דמדומים אזרחיים).', en: 'Sunrise and sunset: the sun’s centre 0.833° below the horizon (allowing for refraction). Golden hour: the sun up to 6° above the horizon. Blue hour: the sun 0–6° below it (civil twilight).' },
  golden:     { he: 'שעת זהב', en: 'Golden hour' },
  blue:       { he: 'שעה כחולה', en: 'Blue hour' },
  dark:       { he: 'חושך', en: 'Dark' },
  st_sunrise_in: { he: 'הזריחה בעוד {t}', en: 'Sunrise in {t}' },
  st_golden_in:  { he: 'שעת הזהב מתחילה בעוד {t}', en: 'Golden hour starts in {t}' },
  st_golden_now: { he: 'שעת הזהב עכשיו — השקיעה בעוד {t}', en: 'Golden hour now — sunset in {t}' },
  st_blue_now:   { he: 'השעה הכחולה עכשיו — חושך בעוד {t}', en: 'Blue hour now — dark in {t}' },
  st_dark:       { he: 'השמש כבר שקעה להיום', en: 'The sun has set for today' },
  today:      { he: 'היום', en: 'Today' },
  tomorrow:   { he: 'מחר', en: 'Tomorrow' },
  other_date: { he: 'תאריך אחר…', en: 'Other date…' },
  polar: { he: 'במקום הזה השמש לא זורחת או לא שוקעת בתאריך הזה', en: 'At this place the sun does not rise or set on this date' },

  volts: { he: 'מתח (V)', en: 'Voltage (V)' },
  back_tools: { he: 'כל הכלים', en: 'All tools' },
};
